# Generated by Django 4.0.2 on 2022-08-01 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('minister_name', models.CharField(max_length=255)),
                ('address_location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('WAP', 'Word and prayer'), ('TSC', 'The School of Christ'), ('BS', 'Bible Study'), ('SWS', 'Sunday Worship Service'), ('KBN', 'Kingdom Business Network'), ('KLS', 'Kingdom Life Summit'), ('ETS', 'Equiping The Saint'), ('TEENS', 'Tenagers')], max_length=255)),
                ('blog_photo_1', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('blog_photo_2', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('blog_photo_3', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('blog_photo_4', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('blog_photo_5', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('blog_body', models.TextField(max_length=5000)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
