# Generated by Django 4.0.2 on 2022-08-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('WAP', 'Word and prayer'), ('TSC', 'The School of Christ'), ('BS', 'Bible Study'), ('SWS', 'Sunday Worship Service'), ('KBN', 'Kingdom Business Network'), ('KLS', 'Kingdom Life Summit'), ('ETS', 'Equiping The Saint'), ('TEENS', 'Tenagers')], max_length=200),
        ),
    ]
