# Generated by Django 4.0.2 on 2022-08-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_audio_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_msg',
            name='id_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
