# Generated by Django 4.0.2 on 2022-08-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_audio_msg_id_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio_msg',
        ),
    ]
