# Generated by Django 4.0.2 on 2022-08-06 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_title', models.CharField(max_length=255)),
                ('minister_name', models.CharField(max_length=255)),
                ('address_location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('WAP', 'Word and prayer'), ('TSC', 'The School of Christ'), ('BS', 'Bible Study'), ('SWS', 'Sunday Worship Service'), ('IMGC', 'Image & Glory Conference'), ('KBN', 'Kingdom Business Network'), ('KLS', 'Kingdom Life Summit'), ('ETS', 'Equiping The Saint'), ('TEENS', 'Tenagers'), ('KCC', 'Kingdom Community Center')], max_length=200)),
                ('blog_photo_1', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('msg_link', models.CharField(max_length=250)),
                ('id_link', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
